### ISSUE TITLE
cannot work on un-align block

### ISSUE THREAD

**Issue by coolicer** [t9md/atom-vim-mode-visual-block#2]
![qq20150723-1 2x](https://cloud.githubusercontent.com/assets/811078/8840876/b31b6ffe-3119-11e5-9c14-b70bd664e3fa.png)

see the pic above, visual-block not working for unalign block. from the `if` begin,press `ctrl+v`, when move down ,it jump to the `else`.the section in `if else` block have not been selected.

**Comment by t9md** [comment]
Currently vim-mode-visual-block depending on Atom's `TextEditor::addSelectionBlow()` and `TextEditor::addSelectionAbove()`.
The behavior you reported is just as how these method behave.

I don't think I can easily fix(or improve) the issue you reported.
And have no motivation for that for now.

Please use `ctrl-shift-up`, `ctrl-shift-down` from `normal-mode` of vim-mode in that case.
