### ISSUE TITLE
visual block jumps down four lines at once

### ISSUE THREAD

**Issue by ghost** [t9md/atom-vim-mode-visual-block#4]
v0.2.9
mac os x yosemite v 10.10.4

inputs:
- ctrl + v
- j

expected output:
visual block mode jumps down one line and spans across two lines 

observed output:
visual block mode jumps down three lines and spans across four lines

**Comment by t9md** [comment]
Strange behavior, I need exact reproducing procedure.
- Example text you work on.
- Grammar
- Softwrap enabled/disabled?

**Comment by imjakeayala** [comment]
Sure thing!

Good news:
- I checked to see if the same configuration works as expected on another laptop Atom installation. It does -- no error there
- I closed my current project folder where I saw the issue, screenshotted my settings to send along, and restarted Atom
- Once restarted, visual block works as expected!

Bad news: 
- Now I do not know how to reproduce the issue. I think it might have had to do with an error that came up from a command attempted in 'ex-mode' that I ran in that particular project. I'm going to close the issue. Thanks for your response

**Comment by ghost** [comment]
Sure thing!

Good news:
- I checked to see if the same configuration works as expected on another laptop Atom installation. It does -- no error there
- I closed my current project folder where I saw the issue, screenshotted my settings to send along, and restarted Atom
- Once restarted, visual block works as expected!

Bad news: 
- Now I do not know how to reproduce the issue. I think it might have had to do with an error that came up from a command attempted in 'ex-mode' that I ran in that particular project. 

That said, I'm going to close the issue. Thanks for your response

**Comment by t9md** [comment]
Thanks for reporting good news and bad news! :smile:
