### ISSUE TITLE
Not working on vim-mode 0.64.0

### ISSUE THREAD

**Issue by axelson** [t9md/atom-vim-mode-visual-block#5]
After upgrading vim-mode to 0.64.0 this morning visual block doesn't appear to fully work. When press `ctrl + v` to enter Atom does go into vim "Visual Block" mode. But when I press `j` to go down the full line is highlighted as if I were in normal visual mode.

Thanks for the plugin! It's been working great so far :+1:

**Comment by t9md** [comment]
Sorry as I put NOTE in README.md.
I have no longer have motivation to maintain this package.
Since I'm actively investing my time for [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus)(fork project of vim-mode).
vim-mode-plus includes visual-block-mode builtin.
