### ISSUE TITLE
How to map to cmd-v?

### ISSUE THREAD

**Issue by trusktr** [t9md/atom-vim-mode-visual-block#6]
I'm new to Atom, and not sure how to make `cmd-v` toggle VISUAL BLOCK.

I tried with no luck:

``` cson
'atom-text-editor.vim-mode.visual-mode':
  'cmd-v': 'vim-mode-visual-block:ctrl-v'
```

based on what I see in the settings, but after looking at the key resolver (cmd-.) I see I may need to make different mappings which aren't obvious from the package's settings page.

**Comment by trusktr** [comment]
Got it:

``` cson
'atom-text-editor.vim-mode-plus.visual-mode':
  'cmd-v': 'vim-mode-plus:activate-blockwise-visual-mode'
'atom-text-editor.vim-mode-plus.normal-mode':
  'cmd-v': 'vim-mode-plus:activate-blockwise-visual-mode'
```

Based on what I saw in the resolver when pressing `ctrl-v`.

**Comment by trusktr** [comment]
Maybe for your vim-mode-plus packages you can add an option to switch ctrl with cmd? The reason is because I have capslock as cmd, so with that cmd-v mapping it means I physically press capslock-v.

**Comment by t9md** [comment]
You can do it by yourself via your `keymap.cson`.
And it's not issue of **this** package? You don't need **this** package if you are using vim-mode-plus and I no longer have interest to maintain **this** package.

**Comment by trusktr** [comment]
Oh!! So, I should install only vim-mode-plus and remove vim-mode-plus-visual-block. Thanks for letting me know. Wasn't obvious when I was searching for "vim-mode-plus" in Atom's package installer.

**Comment by trusktr** [comment]
How do I know which of your plugins require separate install?

**Comment by t9md** [comment]
Read README.md of vim-mode-plus?

**Comment by trusktr** [comment]
Wasn't obvious, it says it's your plugin, "integrated", so, then maybe you should delete the extra package.
