### ISSUE TITLE
How can I disable copy to clipboard

### ISSUE THREAD

**Issue by Jacksgong** [t9md/atom-vim-mode-visual-block#7]
Thanks for your awesome job, it's very useful for me!

Because of my usage habit, It's very unfriendly to me when I use `x` or `dd` to delete something,  the deleted data is not only on the `p` command-board, but also occupied my clipboard.

How can I disable it to occupy my clipboard, thanks!

**Comment by xdays** [comment]
`useClipboardAsDefaultRegister: false`

**Comment by jasonvoor** [comment]
meanwhile there is (also) checkbox-setting in Settings/Packages/vim-mode-plus/Settings:
"Use Clipboard As Default Register". Just uncheck that. @xdays  thanks for pointing me in the right direction :)

**Comment by Jacksgong** [comment]
> meanwhile there is (also) checkbox-setting in Settings/Packages/vim-mode-plus/Settings:
> "Use Clipboard As Default Register". Just uncheck that. @xdays thanks for pointing me in the right direction :)

Awesome, It really resolves the issue!
